### ISSUE TITLE
Call to undefined function geodir_wpml_is_post_type_translated()

### ISSUE THREAD

**Issue by bionemesis** [GeoDirectory/geodir_api#22]
In the latest build, I'm getting the following error when trying to pull up a JSON feed:

<b>Fatal error</b>:  Call to undefined function geodir_wpml_is_post_type_translated() in <b>/home/stagingpetpedia/public_html/wp-content/plugins/geodir_api-master/includes/geodir-rest-listings-functions.php</b> on line <b>1125</b><br />

Uncommenting the WPML section fixes it. Is the plugin perhaps not verifying that WPML is actually installed?

**Comment by Stiofan** [comment]
Hi, that is not a release its still the master stream, you would need to use the master stream of GD core also, but if you are running addons you should wait for them to be released also.

**Comment by bionemesis** [comment]
Thanks Stiofan. What's the best way to get the latest version of the API compatible with the release version of GD core then? I thought the only way to get it was via GitHub.

**Comment by Stiofan** [comment]
At the moment it is, we have not officially started doing releases so its all running of the master track, i'll make sure that is addressed on the next release of GD core.
