### ISSUE TITLE
Add end point for claim listing feature

### ISSUE THREAD

**Issue by lwincmm** [GeoDirectory/geodir_api#26]
waiting to buy plugin after below end points are ready
a) end point for claim listing
b)Endpoints to get packages list & custom fields/create new post based on packaged price payment
c)Endpoint to favorite/un-favorite listing & mark review review useful or not

**Comment by Stiofan** [comment]
The API has been merged into GDv2 core.
Issues should be opened there: https://github.com/AyeCode/geodirectory
