### ISSUE TITLE
social log in/register with mobile app

### ISSUE THREAD

**Issue by lwincmm** [GeoDirectory/geodir_api#28]
Hi,

Found this your product
https://userswp.io/downloads/social-login/

Willing to use it together with geodirectory and thus required in mobile app .
It will be great if you do REST API for this too.
I have no issue to buy both if you add in REST API.

rgds.

**Comment by Stiofan** [comment]
The API has been merged into GDv2 core.
Issues should be opened there: https://github.com/AyeCode/geodirectory
